// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACTwGZ6ob7XlM1bpxLEgNDaN0tvgcCKHM',
    appId: '1:66325138436:web:0ba13f43872e9dd164f951',
    messagingSenderId: '66325138436',
    projectId: 'news-detector-85e3b',
    authDomain: 'news-detector-85e3b.firebaseapp.com',
    storageBucket: 'news-detector-85e3b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv30xS4-0D-pVYCqCWWq0Cp2aic_Jbc8o',
    appId: '1:66325138436:android:c6266452f7d691de64f951',
    messagingSenderId: '66325138436',
    projectId: 'news-detector-85e3b',
    storageBucket: 'news-detector-85e3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpVKqhUcFCmnc7_CVlXFc-GNdxJS-Krpk',
    appId: '1:66325138436:ios:878e2130ea1bb99e64f951',
    messagingSenderId: '66325138436',
    projectId: 'news-detector-85e3b',
    storageBucket: 'news-detector-85e3b.firebasestorage.app',
    iosBundleId: 'com.example.newsDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpVKqhUcFCmnc7_CVlXFc-GNdxJS-Krpk',
    appId: '1:66325138436:ios:878e2130ea1bb99e64f951',
    messagingSenderId: '66325138436',
    projectId: 'news-detector-85e3b',
    storageBucket: 'news-detector-85e3b.firebasestorage.app',
    iosBundleId: 'com.example.newsDetector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACTwGZ6ob7XlM1bpxLEgNDaN0tvgcCKHM',
    appId: '1:66325138436:web:23986651d596044864f951',
    messagingSenderId: '66325138436',
    projectId: 'news-detector-85e3b',
    authDomain: 'news-detector-85e3b.firebaseapp.com',
    storageBucket: 'news-detector-85e3b.firebasestorage.app',
  );
}
